import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import { getSiteData, getAllGameData } from 'helpers/contentApi'
import Layout from 'components/Layout'
import GamePanel from 'components/GamePanel'
import styles from 'styles/Home.module.css'

type HomePageProps = {
  site: SiteData,
  thumbnail: string,
  games: GameData[]
}

const HomePage: NextPage<HomePageProps> = ({ site, thumbnail, games }) => (
  <Layout title={site.title} description={site.description} thumbnail={thumbnail} twitterUrl={site.author.twitterUrl}>
    <div className={styles.container}>
      <Head>
        <title>ayla~nonsense</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ayla~nonsense
        </h1>

        <div className="games">
          {games.map(game =>
            <GamePanel key={game.slug} title={game.title} role={game.role} />
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Bewp</p>
      </footer>
    </div>
  </Layout>
)

export default HomePage;

export const getStaticProps: GetStaticProps<HomePageProps> = async () => {
  const siteRequest = getSiteData()
  const allGamesRequest = getAllGameData()
  const site = await siteRequest
  const games = await allGamesRequest
  return {
    props: {
      site,
      thumbnail: 'TODO.png',
      games
    }
  }
}
